version: 2

builds:
  - main: .
    binary: argazer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}

archives:
  - format: tar.gz
    # Use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

# In argazer we use casks to avoid quarantine issues on macOS and correctly publish to tap
homebrew_casks:
  - repository:
      owner: k-krew
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/kreicer/argazer"
    description: "Monitor ArgoCD applications for Helm chart updates"
    license: "Apache-2.0"
    binaries: [argazer]
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/argazer"]
          end
